# Generated by Django 3.1.5 on 2021-01-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('warranty', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
