# Generated by Django 3.1.5 on 2021-01-26 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=datetime.datetime(2021, 1, 26, 23, 34, 2, 812868, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
