# Generated by Django 3.1.5 on 2021-02-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_m', '0002_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
    ]
