# Generated by Django 3.1.5 on 2021-02-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_m', '0003_auto_20210207_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='warehouse_m/product_img'),
        ),
    ]
