# Generated by Django 3.1.5 on 2021-02-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_m', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='warehouse_m/product_img/no-image.png', upload_to='warehouse_m/product_img'),
        ),
    ]
